"""Initial schema: shows, seasons, episodes, artwork, publish_runs

Revision ID: e82cbf903064
Revises: 
Create Date: 2026-09-04 23:10:48.832437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e82cbf903064'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publish_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('triggered_by', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('show_count', sa.Integer(), nullable=True),
    sa.Column('episode_count', sa.Integer(), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('synopsis', sa.Text(), nullable=True),
    sa.Column('section', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('ix_shows_section_status', 'shows', ['section', 'status'], unique=False)
    op.create_table('seasons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('show_id', sa.UUID(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('show_id', 'number', name='uq_season_show_number')
    )
    op.create_table('episodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('season_id', sa.UUID(), nullable=False),
    sa.Column('content_group', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('categories', sa.ARRAY(sa.String()), nullable=True),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_group', 'language', name='uq_episode_content_group_language')
    )
    op.create_index('ix_episodes_content_group', 'episodes', ['content_group'], unique=False)
    op.create_table('artwork',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('episode_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('storage_key', sa.String(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('episode_id', 'type', name='uq_artwork_episode_type')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artwork')
    op.drop_index('ix_episodes_content_group', table_name='episodes')
    op.drop_table('episodes')
    op.drop_table('seasons')
    op.drop_index('ix_shows_section_status', table_name='shows')
    op.drop_table('shows')
    op.drop_table('publish_runs')
    # ### end Alembic commands ###
